import { StellarNetworkConfig } from '@agriflow/types';

export const STELLAR_TESTNET_CONFIG: StellarNetworkConfig = {
  network: 'TESTNET',
  networkPassphrase: process.env.NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE || 'Test SDF Network ; September 2015',
  horizonUrl: process.env.NEXT_PUBLIC_HORIZON_URL || 'https://horizon-testnet.stellar.org',
  explorerUrl: process.env.NEXT_PUBLIC_EXPLORER_URL || 'https://stellar.expert/explorer/testnet',
};

export const STELLAR_SOROBAN_RPC_URL =
  process.env.NEXT_PUBLIC_SOROBAN_RPC_URL || 'https://soroban-testnet.stellar.org';

// Deployed Soroban Smart Contracts on Stellar Testnet
export const FARM_REGISTRY_CONTRACT_ID =
  process.env.NEXT_PUBLIC_FARM_REGISTRY_CONTRACT_ID ||
  'CBLQUEAJAI6PYQDEWQR2ICR2FPPP6KQN5ZEGPT4FD7MXCGBJZTOO2CDZ';

export const AGRICULTURAL_REPUTATION_CONTRACT_ID =
  process.env.NEXT_PUBLIC_AGRICULTURAL_REPUTATION_CONTRACT_ID ||
  'CBUME23GQVEJ5SWDA7EOTUFOGXSSC2RO5HFTUMXQDQOPWTGOM2YWU65S';

export const AGRICULTURAL_ESCROW_CONTRACT_ID =
  process.env.NEXT_PUBLIC_AGRICULTURAL_ESCROW_CONTRACT_ID ||
  'CD72TIQ3LQKJJKQX44UJVF6CT2V6FLELKXQPZ6TZ66KUYLLGUHQI7RHD';

export const AGRICULTURAL_MARKETPLACE_CONTRACT_ID =
  process.env.NEXT_PUBLIC_AGRICULTURAL_MARKETPLACE_CONTRACT_ID ||
  'CD4RQ6D36NCTEXG22BPI3VBHZYJMES7CVS5Z7YLP4TJM3BI6IMHTVPF5';

export const AGRICULTURAL_FINANCE_CONTRACT_ID =
  process.env.NEXT_PUBLIC_AGRICULTURAL_FINANCE_CONTRACT_ID ||
  'CBRTDNZPZYCKUO7U76DEWV32KAYXZ45JPL2FUPCJIKQIA47BWXZFMBCL';

export const STELLAR_BASE_FEE_STROOPS = '100';
export const STELLAR_BASE_RESERVE_XLM = 0.5;
export const STELLAR_MIN_ACCOUNT_RESERVE = 1.0;
